# Generated by Django 5.1.1 on 2024-09-12 07:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_users_face_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
