# Generated by Django 5.1.1 on 2024-09-12 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_users_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='purpose_of_visit',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='visiting_whom',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
